<?php

use App\Http\Controllers\Api\V1\AuthController;
use App\Http\Controllers\Api\V1\LocationController;
use App\Http\Controllers\Api\V1\OperationsDashboardController;
use App\Http\Controllers\Api\V1\UserManagementController;
use App\Http\Controllers\Api\V1\RoleController;
use App\Http\Controllers\Api\V1\InvitationController;
use App\Http\Controllers\Api\V1\AccountController;
use App\Http\Controllers\Api\V1\SystemSettingsController;
use App\Http\Controllers\Api\V1\MediaLibraryController;
use App\Http\Controllers\Api\V1\RegistrationController;
use App\Http\Controllers\Api\V1\CalendarController;
use App\Http\Controllers\Api\V1\PasswordResetController;
use App\Http\Controllers\Api\V1\OrganizationStructureController;
use App\Http\Controllers\Api\V1\AnnouncementController;
use App\Http\Controllers\Api\V1\PolicyController;
use App\Http\Controllers\Api\V1\FrontendReadController;
use App\Http\Controllers\Api\V1\MasterDataController;
use App\Http\Controllers\Api\V1\PriceListController;
use App\Http\Controllers\Api\V1\ReportController;
use App\Http\Controllers\Api\V1\BackupController;
use App\Http\Controllers\Api\V1\DataExchangeController;
use App\Http\Controllers\Api\V1\StockController;
use App\Http\Controllers\Api\V1\PurchaseOrderController;
use App\Http\Controllers\Api\V1\DepartmentWorkspaceController;
use App\Http\Controllers\Api\V1\NotificationController;
use App\Http\Controllers\Api\V1\OfflineSyncController;
use App\Http\Controllers\Api\V1\GlobalSearchController;
use App\Http\Controllers\Api\V1\PettyCashController;
use App\Http\Controllers\Api\V1\SupplierController;
use App\Http\Controllers\Api\V1\VehicleController;
use App\Http\Controllers\Api\V1\WorkshopStaffController;
use App\Http\Controllers\Api\V1\WorkshopIssueController;
use App\Http\Controllers\Api\V1\WarehouseLocatorController;
use Illuminate\Support\Facades\Route;

Route::prefix('v1')->group(function () {
    Route::post('/auth/login', [AuthController::class, 'login'])->middleware('throttle:5,1')->name('auth.login');
    Route::post('/auth/register', [RegistrationController::class, 'register'])->middleware('throttle:5,1')->name('auth.register');
    Route::post('/auth/verify-email', [RegistrationController::class, 'verify'])->middleware('throttle:10,1')->name('auth.verify');
    Route::post('/auth/resend-code', [RegistrationController::class, 'resend'])->middleware('throttle:3,1')->name('auth.resend');
    Route::post('/auth/forgot-password', [PasswordResetController::class, 'requestLink'])->middleware('throttle:3,1')->name('auth.password.email');
    Route::post('/auth/reset-password', [PasswordResetController::class, 'reset'])->middleware('throttle:5,1')->name('auth.password.reset');
    Route::post('/invitations/accept', [InvitationController::class, 'accept'])->middleware('throttle:5,1')->name('invitations.accept');

    Route::middleware(['api.token', 'audit.api'])->group(function () {
        Route::get('/auth/me', [AuthController::class, 'me'])->name('auth.me');
        Route::post('/auth/unlock', [AuthController::class, 'unlock'])->middleware('throttle:5,1')->name('auth.unlock');
        Route::post('/auth/logout', [AuthController::class, 'logout'])->name('auth.logout');
        Route::match(['post', 'patch'], '/account/profile', [AccountController::class, 'updateProfile'])->name('account.profile');
        Route::post('/account/password', [AccountController::class, 'changePassword'])->middleware('throttle:5,1')->name('account.password');
        Route::get('/settings', [SystemSettingsController::class, 'show'])->middleware('permission:users.manage')->name('settings.show');
        Route::patch('/settings', [SystemSettingsController::class, 'update'])->middleware('permission:users.manage')->name('settings.update');
        Route::patch('/settings/{section}', [SystemSettingsController::class, 'updateSection'])->middleware('permission:users.manage')->whereIn('section', ['email', 'recaptcha', 'cookie'])->name('settings.section.update');
        Route::post('/settings/email/test', [SystemSettingsController::class, 'testEmail'])->middleware(['permission:users.manage', 'throttle:3,1'])->name('settings.email.test');
        Route::post('/settings/cache/clear', [SystemSettingsController::class, 'clearCache'])->middleware(['permission:users.manage', 'throttle:3,1'])->name('settings.cache.clear');
        Route::middleware('permission:users.manage')->group(function(){ Route::get('/backups',[BackupController::class,'index']); Route::patch('/backups/settings',[BackupController::class,'update']); Route::post('/backups',[BackupController::class,'store'])->middleware('throttle:2,1'); Route::get('/backups/{backup}/download',[BackupController::class,'download']); Route::delete('/backups/{backup}',[BackupController::class,'destroy']); });
        Route::post('/data-exchange/export-authorize',[DataExchangeController::class,'authorizeExport'])->middleware('permission:data.export');
        Route::post('/data-exchange/import/{resource}',[DataExchangeController::class,'import'])->middleware('permission:data.import');
        Route::get('/search', GlobalSearchController::class)->name('search.global');
        Route::get('/policies', [PolicyController::class, 'index'])->name('policies.index');
        Route::patch('/policies/{slug}', [PolicyController::class, 'update'])->middleware('throttle:30,1')->name('policies.update');
        Route::get('/vehicles', [VehicleController::class, 'index'])->middleware('permission:vehicles.view');
        Route::post('/vehicles', [VehicleController::class, 'store'])->middleware('permission:vehicles.manage');
        Route::post('/vehicles/import', [VehicleController::class, 'import'])->middleware('permission:vehicles.manage');
        Route::patch('/vehicles/{vehicle}', [VehicleController::class, 'update'])->middleware('permission:vehicles.manage');
        Route::delete('/vehicles/{vehicle}', [VehicleController::class, 'destroy'])->middleware('permission:vehicles.manage');
        Route::get('/staff', [WorkshopStaffController::class, 'index'])->middleware('permission:staff.view');
        Route::post('/staff', [WorkshopStaffController::class, 'store'])->middleware('permission:staff.manage');
        Route::post('/staff/import', [WorkshopStaffController::class, 'import'])->middleware('permission:staff.manage');
        Route::patch('/staff/{staff}', [WorkshopStaffController::class, 'update'])->middleware('permission:staff.manage');
        Route::delete('/staff/{staff}', [WorkshopStaffController::class, 'destroy'])->middleware('permission:staff.manage');
        Route::get('/workshop-issues', [WorkshopIssueController::class, 'index'])->middleware('permission:workshop.issues.view');
        Route::post('/workshop-issues', [WorkshopIssueController::class, 'store'])->middleware('permission:workshop.issues.create');
        Route::get('/media', [MediaLibraryController::class, 'index'])->middleware('permission:media.view')->name('media.index');
        Route::post('/media', [MediaLibraryController::class, 'upload'])->middleware('permission:users.manage')->name('media.upload');
        Route::post('/media/folders', [MediaLibraryController::class, 'createFolder'])->middleware('permission:users.manage')->name('media.folders.store');
        Route::delete('/media/{asset}', [MediaLibraryController::class, 'destroy'])->middleware('permission:users.manage')->name('media.destroy');
        Route::get('/calendar', [CalendarController::class, 'index'])->middleware('permission_any:calendar.view,locations.view')->name('calendar.index');
        Route::post('/calendar', [CalendarController::class, 'store'])->middleware('permission_any:calendar.manage,locations.manage')->name('calendar.store');
        Route::get('/locations', [LocationController::class, 'index'])->middleware('permission:locations.view')->name('locations.index');
        Route::middleware('permission:locations.view')->group(function () { Route::get('/companies', [OrganizationStructureController::class, 'companies']); Route::get('/storage-locations', [OrganizationStructureController::class, 'warehouses']); });
        Route::middleware('permission_any:departments.view,locations.view')->group(function () { Route::get('/branches', [OrganizationStructureController::class, 'branches']); Route::get('/departments', [OrganizationStructureController::class, 'departments']); });
        Route::middleware('permission:locations.manage')->group(function () { Route::patch('/companies/current', [OrganizationStructureController::class, 'updateCompany']); Route::post('/branches', [OrganizationStructureController::class, 'storeBranch']); Route::patch('/branches/{branch}', [OrganizationStructureController::class, 'updateBranch']); Route::delete('/branches/{branch}', [OrganizationStructureController::class, 'destroyBranch']); Route::post('/storage-locations/{type}', [OrganizationStructureController::class, 'storeLocation'])->whereIn('type', ['store','warehouse']); Route::patch('/storage-locations/{type}/{id}', [OrganizationStructureController::class, 'updateLocation'])->whereIn('type', ['store','warehouse']); Route::delete('/storage-locations/{type}/{id}', [OrganizationStructureController::class, 'destroyLocation'])->whereIn('type', ['store','warehouse']); });
        Route::middleware('permission_any:departments.manage,locations.manage')->group(function () { Route::post('/departments', [OrganizationStructureController::class, 'storeDepartment']); Route::patch('/departments/{department}', [OrganizationStructureController::class, 'updateDepartment']); Route::delete('/departments/{department}', [OrganizationStructureController::class, 'destroyDepartment']); });
        Route::post('/companies', [OrganizationStructureController::class, 'storeCompany'])->middleware('permission:locations.manage'); Route::patch('/companies/{organization}', [OrganizationStructureController::class, 'updateCompanyById'])->middleware('permission:locations.manage'); Route::delete('/companies/{organization}', [OrganizationStructureController::class, 'destroyCompany'])->middleware('permission:locations.manage'); Route::get('/inventory/issues', [StockController::class, 'issues'])->middleware('permission:inventory.view'); Route::post('/inventory/issues', [StockController::class, 'issue'])->middleware('permission:stock.issue');
        Route::get('/dashboard/operations', OperationsDashboardController::class)->name('dashboard.operations');
        Route::get('/supplier-catalog/{supplier}', [SupplierController::class, 'catalog'])->middleware('permission_any:supplier_catalog.manage,suppliers.view'); Route::post('/supplier-catalog/{supplier}/items', [SupplierController::class, 'storeMapping'])->middleware('permission_any:supplier_catalog.manage,master_data.manage'); Route::patch('/supplier-catalog/{supplier}/items/{mapping}', [SupplierController::class, 'updateMapping'])->middleware('permission_any:supplier_catalog.manage,master_data.manage'); Route::delete('/supplier-catalog/{supplier}/items/{mapping}', [SupplierController::class, 'destroyMapping'])->middleware('permission_any:supplier_catalog.manage,master_data.manage');
        Route::get('/dashboard/stats', [FrontendReadController::class, 'dashboardStats']);
        Route::get('/dashboard/sales-chart', [FrontendReadController::class, 'emptyList']); Route::get('/dashboard/recent-activity', [FrontendReadController::class, 'emptyList']); Route::get('/dashboard/top-products', [FrontendReadController::class, 'emptyList']);
        Route::get('/products', [MasterDataController::class, 'products'])->middleware('permission:inventory.view'); Route::post('/products', [MasterDataController::class, 'storeProduct'])->middleware('permission:master_data.manage'); Route::get('/products/{product}', [MasterDataController::class, 'showProduct'])->middleware('permission:inventory.view'); Route::patch('/products/{product}', [MasterDataController::class, 'updateProduct'])->middleware('permission:master_data.manage'); Route::delete('/products/{product}', [MasterDataController::class, 'destroyProduct'])->middleware('permission:master_data.manage'); Route::patch('/products/{product}/active', [MasterDataController::class, 'toggleProduct'])->middleware('permission:master_data.manage');
        Route::get('/categories', [MasterDataController::class, 'categories'])->middleware('permission:inventory.view'); Route::post('/categories', [MasterDataController::class, 'storeCategory'])->middleware('permission:master_data.manage'); Route::patch('/categories/{category}', [MasterDataController::class, 'updateCategory'])->middleware('permission:master_data.manage'); Route::delete('/categories/{category}', [MasterDataController::class, 'destroyCategory'])->middleware('permission:master_data.manage'); Route::get('/units', [MasterDataController::class, 'units'])->middleware('permission:inventory.view'); Route::post('/units', [MasterDataController::class, 'storeUnit'])->middleware('permission:master_data.manage'); Route::delete('/units/{unit}', [MasterDataController::class, 'destroyUnit'])->middleware('permission:master_data.manage'); Route::get('/inventory/adjustments', [StockController::class, 'index'])->middleware('permission:inventory.view'); Route::post('/inventory/adjustments', [StockController::class, 'adjust'])->middleware('permission:stock.adjust'); Route::post('/inventory/transfers', [StockController::class, 'transfer'])->middleware('permission:stock.transfer.dispatch'); Route::get('/inventory/valuation', [StockController::class, 'valuation'])->middleware('permission:inventory.view');
        Route::get('/customers', [MasterDataController::class, 'customers'])->middleware('permission:customers.view'); Route::post('/customers', [MasterDataController::class, 'storeCustomer'])->middleware('permission:master_data.manage'); Route::patch('/customers/{customer}', [MasterDataController::class, 'updateCustomer'])->middleware('permission:master_data.manage'); Route::delete('/customers/{customer}', [MasterDataController::class, 'destroyCustomer'])->middleware('permission:master_data.manage'); Route::get('/suppliers', [MasterDataController::class, 'suppliers'])->middleware('permission:suppliers.view'); Route::get('/suppliers/{supplierId}/stats', [PurchaseOrderController::class, 'supplierStats'])->middleware('permission:suppliers.view'); Route::get('/suppliers/{supplier}/profile', [SupplierController::class, 'profile'])->middleware('permission:suppliers.view'); Route::get('/suppliers/{supplier}/documents', [SupplierController::class, 'documents'])->middleware('permission_any:suppliers.view,supplier_documents.upload'); Route::post('/suppliers/{supplier}/contacts', [SupplierController::class, 'storeContact'])->middleware('permission:master_data.manage'); Route::patch('/suppliers/{supplier}/contacts/{contact}', [SupplierController::class, 'updateContact'])->middleware('permission:master_data.manage'); Route::delete('/suppliers/{supplier}/contacts/{contact}', [SupplierController::class, 'destroyContact'])->middleware('permission:master_data.manage'); Route::patch('/suppliers/{supplier}/commercial-terms', [SupplierController::class, 'updateTerms'])->middleware('permission:master_data.manage'); Route::post('/suppliers/{supplier}/mappings', [SupplierController::class, 'storeMapping'])->middleware('permission:master_data.manage'); Route::patch('/suppliers/{supplier}/mappings/{mapping}', [SupplierController::class, 'updateMapping'])->middleware('permission:master_data.manage'); Route::delete('/suppliers/{supplier}/mappings/{mapping}', [SupplierController::class, 'destroyMapping'])->middleware('permission:master_data.manage'); Route::post('/suppliers/{supplier}/documents', [SupplierController::class, 'uploadDocument'])->middleware('permission_any:master_data.manage,supplier_documents.upload'); Route::get('/suppliers/{supplier}/documents/{document}/download', [SupplierController::class, 'downloadDocument'])->middleware('permission_any:suppliers.view,supplier_documents.upload'); Route::delete('/suppliers/{supplier}/documents/{document}', [SupplierController::class, 'destroyDocument'])->middleware('permission_any:master_data.manage,supplier_documents.upload'); Route::post('/suppliers', [MasterDataController::class, 'storeSupplier'])->middleware('permission:master_data.manage'); Route::patch('/suppliers/{supplier}', [MasterDataController::class, 'updateSupplier'])->middleware('permission:master_data.manage'); Route::delete('/suppliers/{supplier}', [MasterDataController::class, 'destroySupplier'])->middleware('permission:master_data.manage');
        Route::get('/warehouses', [FrontendReadController::class, 'warehouses'])->middleware('permission:locations.view'); Route::get('/warehouses/{warehouse}/stock', [StockController::class, 'warehouseStock'])->middleware('permission:locations.view'); Route::get('/warehouses/{warehouse}/stats', [StockController::class, 'warehouseStats'])->middleware('permission:locations.view'); Route::post('/warehouses', [MasterDataController::class, 'storeWarehouse'])->middleware('permission:locations.manage'); Route::patch('/warehouses/{warehouse}', [MasterDataController::class, 'updateWarehouse'])->middleware('permission:locations.manage'); Route::delete('/warehouses/{warehouse}', [MasterDataController::class, 'destroyWarehouse'])->middleware('permission:locations.manage'); Route::get('/sales', [FrontendReadController::class, 'emptyList'])->middleware('permission:sales.view'); Route::get('/sales/daily-summary', [FrontendReadController::class, 'dailySummary'])->middleware('permission:sales.view');
        Route::get('/warehouse-locator', [WarehouseLocatorController::class, 'index'])->middleware('permission:warehouse_locator.view'); Route::patch('/warehouse-locator/{product}', [WarehouseLocatorController::class, 'update'])->middleware('permission:warehouse_locator.manage');
        Route::get('/department-workspace', [DepartmentWorkspaceController::class, 'index'])->middleware('permission:department.view'); Route::post('/department-workspace/orders', [DepartmentWorkspaceController::class, 'storeOrder'])->middleware('permission:department.orders.create');
        Route::get('/purchase-orders', [PurchaseOrderController::class, 'index'])->middleware('permission_any:purchase_orders.view,supplier_orders.view'); Route::post('/purchase-orders', [PurchaseOrderController::class, 'store'])->middleware('permission:purchase_orders.create'); Route::get('/purchase-orders/{purchaseOrder}', [PurchaseOrderController::class, 'show'])->middleware('permission_any:purchase_orders.view,supplier_orders.view'); Route::patch('/purchase-orders/{purchaseOrder}/profile', [PurchaseOrderController::class, 'updateProfile'])->middleware('permission:purchase_orders.view'); Route::post('/purchase-orders/{purchaseOrder}/documents', [PurchaseOrderController::class, 'uploadDocument'])->middleware('permission:purchase_orders.view'); Route::get('/purchase-orders/{purchaseOrder}/documents/{document}/download', [PurchaseOrderController::class, 'downloadDocument'])->middleware('permission_any:purchase_orders.view,supplier_orders.view'); Route::delete('/purchase-orders/{purchaseOrder}/documents/{document}', [PurchaseOrderController::class, 'destroyDocument'])->middleware('permission:purchase_orders.view'); Route::post('/purchase-orders/{purchaseOrder}/comments', [PurchaseOrderController::class, 'storeComment'])->middleware('permission:purchase_orders.view'); Route::patch('/purchase-orders/{purchaseOrder}/status', [PurchaseOrderController::class, 'updateStatus']); Route::post('/purchase-orders/{purchaseOrder}/receipts', [PurchaseOrderController::class, 'receive'])->middleware('permission:goods_receipts.create'); Route::post('/purchase-orders/{purchaseOrder}/payments', [PurchaseOrderController::class, 'recordPayment'])->middleware('permission:purchase_orders.payment_verify'); Route::get('/replenishment-requests', [StockController::class, 'replenishmentRequests'])->middleware('permission:requisitions.view'); Route::post('/replenishment-requests', [StockController::class, 'createReplenishmentRequest'])->middleware('permission:requisitions.create'); Route::get('/shipments', [FrontendReadController::class, 'emptyList'])->middleware('permission:logistics.view');
        Route::get('/petty-cash', [PettyCashController::class, 'index'])->middleware('permission:petty_cash.view'); Route::post('/petty-cash', [PettyCashController::class, 'store'])->middleware('permission:petty_cash.create'); Route::post('/petty-cash/{pettyCash}/documents', [PettyCashController::class, 'uploadDocument'])->middleware('permission:petty_cash.create'); Route::get('/petty-cash/{pettyCash}/documents/{document}/download', [PettyCashController::class, 'downloadDocument'])->middleware('permission:petty_cash.view'); Route::delete('/petty-cash/{pettyCash}/documents/{document}', [PettyCashController::class, 'destroyDocument'])->middleware('permission:petty_cash.create'); Route::post('/petty-cash/{pettyCash}/comments', [PettyCashController::class, 'storeComment'])->middleware('permission:petty_cash.view'); Route::get('/petty-cash/{pettyCash}', [PettyCashController::class, 'show'])->middleware('permission:petty_cash.view');
        Route::get('/reports/templates', [ReportController::class, 'templates'])->middleware('permission:reports.view');
        Route::get('/reports/{report}', [ReportController::class, 'show'])->middleware('permission:reports.view');
        Route::apiResource('price-lists', PriceListController::class)->only(['index','store','show','update','destroy']); Route::post('/price-lists/{priceList}/items',[PriceListController::class,'storeItem']); Route::patch('/price-lists/{priceList}/items/{item}',[PriceListController::class,'updateItem']); Route::delete('/price-lists/{priceList}/items/{item}',[PriceListController::class,'destroyItem']);
        Route::apiResource('announcements', AnnouncementController::class)->only(['index','show'])->middleware('permission:announcements.view'); Route::apiResource('announcements', AnnouncementController::class)->only(['store','update','destroy'])->middleware('permission:announcements.manage');
        Route::get('/notifications', [NotificationController::class, 'index'])->name('notifications.index');
        Route::get('/notifications/stream', [NotificationController::class, 'stream'])->name('notifications.stream');
        Route::patch('/notifications/{notification}/read', [NotificationController::class, 'markRead'])->name('notifications.read');
        Route::post('/notifications/read-all', [NotificationController::class, 'markAllRead'])->name('notifications.read-all');
        Route::post('/notifications/broadcast', [NotificationController::class, 'broadcast'])->middleware('permission:users.manage')->name('notifications.broadcast');
        Route::get('/notifications/preferences', [NotificationController::class, 'preferences'])->name('notifications.preferences');
        Route::patch('/notifications/preferences/{eventType}', [NotificationController::class, 'updatePreference'])->name('notifications.preferences.update');
        Route::get('/notifications/rules', [NotificationController::class, 'rules'])->middleware('permission:notifications.manage')->name('notifications.rules');
        Route::patch('/notifications/rules/{eventType}', [NotificationController::class, 'updateRule'])->middleware('permission:notifications.manage')->name('notifications.rules.update');
        Route::get('/offline/snapshot', [OfflineSyncController::class, 'snapshot'])->middleware('permission_any:inventory.view,stock.count,stock.issue,stock.adjust,stock.transfer.dispatch');
        Route::get('/offline/operations', [OfflineSyncController::class, 'index'])->middleware('permission_any:inventory.view,stock.count,stock.issue,stock.adjust,stock.transfer.dispatch');
        Route::post('/offline/sync', [OfflineSyncController::class, 'sync'])->middleware('permission_any:stock.count,stock.issue,stock.adjust,stock.transfer.dispatch');
        Route::post('/offline/operations/{operation}/retry', [OfflineSyncController::class, 'retry'])->middleware('permission_any:stock.count,stock.issue,stock.adjust,stock.transfer.dispatch');
        Route::get('/users', [UserManagementController::class, 'index'])->middleware('permission:users.view')->name('users.index');
        Route::patch('/users/{user}', [UserManagementController::class, 'update'])->middleware('permission:users.manage')->name('users.update');
        Route::delete('/users/{user}', [UserManagementController::class, 'destroy'])->middleware('permission:users.manage')->name('users.destroy');
        Route::get('/roles', [RoleController::class, 'index'])->middleware('permission:users.view')->name('roles.index');
        Route::post('/roles', [RoleController::class, 'store'])->middleware('permission:roles.assign')->name('roles.store');
        Route::patch('/roles/{role}', [RoleController::class, 'update'])->middleware('permission:roles.assign')->name('roles.update');
        Route::delete('/roles/{role}', [RoleController::class, 'destroy'])->middleware('permission:roles.assign')->name('roles.destroy');
        Route::get('/invitations', [InvitationController::class, 'index'])->middleware('permission:users.view')->name('invitations.index');
        Route::post('/invitations', [InvitationController::class, 'store'])->middleware(['permission:users.manage', 'permission:roles.assign'])->name('invitations.store');
        Route::post('/invitations/{invitation}/revoke', [InvitationController::class, 'revoke'])->middleware('permission:users.manage')->name('invitations.revoke');
    });
});
