<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller; use App\Mail\BackupCompletedMail; use App\Models\SystemBackup; use App\Services\{DatabaseBackupService,MailDeliveryService}; use App\Support\ApiResponse; use Illuminate\Http\{JsonResponse,Request}; use Illuminate\Support\Facades\Storage; use Illuminate\Validation\Rule; use Symfony\Component\HttpFoundation\StreamedResponse;
class BackupController extends Controller {
 public function index(Request $r):JsonResponse{$org=$r->user()->organization;$settings=array_merge(['automatic'=>false,'frequency'=>'weekly','retention_days'=>30,'email_copy'=>false,'include_uploads'=>true,'storage'=>'local'],data_get($org->settings,'backup',[]));$items=SystemBackup::where('organization_id',$org->id)->latest()->get()->map(fn($b)=>$this->payload($b));return ApiResponse::success(['settings'=>$settings,'backups'=>$items,'last_backup'=>$items->first(),'scheduler_last_seen'=>null]);}
 public function update(Request $r):JsonResponse{$d=$r->validate(['automatic'=>'required|boolean','frequency'=>['required',Rule::in(['daily','weekly','monthly'])],'retention_days'=>'required|integer|between:1,3650','email_copy'=>'required|boolean','include_uploads'=>'required|boolean','storage'=>['required',Rule::in(['local'])]]);$org=$r->user()->organization;$settings=$org->settings??[];$settings['backup']=$d;$org->update(['settings'=>$settings]);return $this->index($r);}
 public function store(Request $r,DatabaseBackupService $service,MailDeliveryService $mailer):JsonResponse{$d=$r->validate(['include_uploads'=>'required|boolean']);$organization=$r->user()->organization;$backup=$service->create($organization,$r->user(),$d['include_uploads']);$emailWarning=null;if((bool)data_get($organization->settings,'backup.email_copy',false)&&filled($r->user()->email)){try{$mailer->send($organization,$r->user()->email,$r->user()->name,new BackupCompletedMail($backup,$organization));}catch(\Throwable $e){report($e);$emailWarning='Backup completed, but the email copy could not be delivered.';}}$payload=$this->payload($backup);if($emailWarning)$payload['email_warning']=$emailWarning;return ApiResponse::success($payload,'Backup completed.',201);}
 public function download(Request $r,SystemBackup $backup):StreamedResponse{$this->owned($r,$backup);abort_unless(Storage::disk($backup->disk)->exists($backup->path),404,'Backup file is missing.');return Storage::disk($backup->disk)->download($backup->path,$backup->filename,['Content-Type'=>'application/zip']);}
 public function destroy(Request $r,SystemBackup $backup):JsonResponse{$this->owned($r,$backup);Storage::disk($backup->disk)->delete($backup->path);$backup->delete();return ApiResponse::success(['deleted'=>true]);}
 private function owned(Request $r,SystemBackup $b):void{abort_unless($b->organization_id===$r->user()->organization_id,404);} private function payload(SystemBackup $b):array{return ['id'=>$b->id,'filename'=>$b->filename,'size'=>$b->size,'checksum'=>$b->checksum,'includes_uploads'=>$b->includes_uploads,'status'=>$b->status,'created_at'=>$b->created_at?->toIso8601String(),'download_url'=>'/backups/'.$b->id.'/download'];}
}
