<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller; use App\Models\{Category,Customer,Product,PurchaseOrder,Supplier,Unit,Warehouse}; use App\Support\ApiResponse; use Illuminate\Database\Eloquent\Model; use Illuminate\Http\{JsonResponse,Request}; use Illuminate\Support\Facades\DB; use Illuminate\Validation\Rule;
class MasterDataController extends Controller {
 private function org(Request $r):int{return (int)$r->user()->organization_id;} private function owned(Request $r,Model $m):void{abort_unless((int)$m->organization_id===$this->org($r),404);}
 public function categories(Request $r):JsonResponse{return response()->json(Category::where('organization_id',$this->org($r))->orderBy('name')->get()->map(fn($x)=>$this->categoryPayload($x)));}
 public function storeCategory(Request $r):JsonResponse{$d=$r->validate(['name'=>['required','string','max:255',Rule::unique('categories')->where('organization_id',$this->org($r))],'description'=>['nullable','string'],'color'=>['nullable','string','max:20']]);$x=Category::create($d+['organization_id'=>$this->org($r)]);return response()->json($this->categoryPayload($x),201);}
 public function updateCategory(Request $r,Category $category):JsonResponse{$this->owned($r,$category);$d=$r->validate(['name'=>['required','string','max:255',Rule::unique('categories')->where('organization_id',$this->org($r))->ignore($category)],'description'=>['nullable','string'],'color'=>['nullable','string','max:20']]);$category->update($d);return response()->json($this->categoryPayload($category));}
 public function destroyCategory(Request $r,Category $category):JsonResponse{$this->owned($r,$category);abort_if(Product::where('category_id',$category->id)->exists(),422,'Category is used by products.');$category->delete();return response()->json(['deleted'=>true]);}
 public function units(Request $r):JsonResponse{return response()->json(Unit::where('organization_id',$this->org($r))->orderBy('name')->get()->map(fn($x)=>['_id'=>(string)$x->id,'name'=>$x->name,'abbreviation'=>$x->abbreviation]));}
 public function storeUnit(Request $r):JsonResponse{$d=$r->validate(['name'=>['required','string','max:255',Rule::unique('units')->where('organization_id',$this->org($r))],'abbreviation'=>['required','string','max:20']]);$x=Unit::create($d+['organization_id'=>$this->org($r)]);return response()->json(['_id'=>(string)$x->id]+$d,201);}
 public function destroyUnit(Request $r,Unit $unit):JsonResponse{$this->owned($r,$unit);$unit->delete();return response()->json(['deleted'=>true]);}
 public function products(Request $r):JsonResponse{return response()->json(Product::with(['category:id,name','unit:id,name'])->where('organization_id',$this->org($r))->orderBy('name')->get()->map(fn($x)=>$this->productPayload($x)));}
 public function showProduct(Request $r,Product $product):JsonResponse{$this->owned($r,$product);return response()->json($this->productPayload($product->load(['category:id,name','unit:id,name','stockBalances.warehouse:id,name'])));}
 public function storeProduct(Request $r):JsonResponse{return $this->saveProduct($r,new Product);}
 public function updateProduct(Request $r,Product $product):JsonResponse{$this->owned($r,$product);return $this->saveProduct($r,$product);}
 public function destroyProduct(Request $r,Product $product):JsonResponse{$this->owned($r,$product);try{$product->delete();}catch(\Illuminate\Database\QueryException $e){abort(422,'Product has stock or transaction history and cannot be deleted. Archive it instead.');}return response()->json(['deleted'=>true]);}
 public function toggleProduct(Request $r,Product $product):JsonResponse{$this->owned($r,$product);$product->update(['is_active'=>!$product->is_active]);return response()->json($this->productPayload($product));}
 public function suppliers(Request $r):JsonResponse{return response()->json(Supplier::where('organization_id',$this->org($r))->orderBy('name')->get()->map(fn($x)=>$this->partyPayload($x)));}
 public function storeSupplier(Request $r):JsonResponse{return $this->saveParty($r,new Supplier,'supplier');} public function updateSupplier(Request $r,Supplier $supplier):JsonResponse{$this->owned($r,$supplier);return $this->saveParty($r,$supplier,'supplier');} public function destroySupplier(Request $r,Supplier $supplier):JsonResponse{$this->owned($r,$supplier);$mode=$r->validate(['mode'=>['required',Rule::in(['keep_history','delete_history'])]])['mode'];return DB::transaction(function()use($supplier,$mode){$orders=PurchaseOrder::where('supplier_id',$supplier->id);$orderCount=(clone $orders)->count();if($mode==='delete_history'){$orders->delete();}else{$orders->update(['supplier_id'=>null]);}$supplier->delete();return response()->json(['deleted'=>true,'mode'=>$mode,'purchaseOrdersAffected'=>$orderCount]);});}
 public function customers(Request $r):JsonResponse{return response()->json(Customer::where('organization_id',$this->org($r))->orderBy('name')->get()->map(fn($x)=>$this->partyPayload($x)));}
 public function storeCustomer(Request $r):JsonResponse{return $this->saveParty($r,new Customer,'customer');} public function updateCustomer(Request $r,Customer $customer):JsonResponse{$this->owned($r,$customer);return $this->saveParty($r,$customer,'customer');} public function destroyCustomer(Request $r,Customer $customer):JsonResponse{$this->owned($r,$customer);$customer->delete();return response()->json(['deleted'=>true]);}
 public function storeWarehouse(Request $r):JsonResponse{return $this->saveWarehouse($r,new Warehouse);} public function updateWarehouse(Request $r,Warehouse $warehouse):JsonResponse{$this->owned($r,$warehouse);return $this->saveWarehouse($r,$warehouse);} public function destroyWarehouse(Request $r,Warehouse $warehouse):JsonResponse{$this->owned($r,$warehouse);$warehouse->update(['is_active'=>false]);return response()->json(['deactivated'=>true]);}
 private function saveProduct(Request $r,Product $x):JsonResponse{$d=$r->validate(['sku'=>['required','string','max:100',Rule::unique('products')->where('organization_id',$this->org($r))->ignore($x)],'name'=>['required','string','max:255'],'description'=>['nullable','string'],'costPrice'=>['required','numeric','min:0'],'sellingPrice'=>['required','numeric','min:0'],'taxRate'=>['nullable','numeric','min:0'],'reorderLevel'=>['nullable','numeric','min:0'],'expiresAt'=>['nullable','date'],'barcode'=>['nullable','string','max:100'],'imageUrl'=>['nullable','string','max:2048'],'categoryId'=>['nullable','integer',Rule::exists('categories','id')->where('organization_id',$this->org($r))],'unitId'=>['nullable','integer',Rule::exists('units','id')->where('organization_id',$this->org($r))],'tags'=>['nullable','array']]);$x->fill(['organization_id'=>$this->org($r),'sku'=>$d['sku'],'name'=>$d['name'],'description'=>$d['description']??null,'cost_price'=>$d['costPrice'],'selling_price'=>$d['sellingPrice'],'tax_rate'=>$d['taxRate']??0,'reorder_level'=>$d['reorderLevel']??0,'expires_at'=>$d['expiresAt']??null,'barcode'=>$d['barcode']??null,'image_url'=>$d['imageUrl']??null,'category_id'=>$d['categoryId']??null,'unit_id'=>$d['unitId']??null,'tags'=>$d['tags']??[]])->save();return response()->json($this->productPayload($x),$x->wasRecentlyCreated?201:200);}
 private function saveParty(Request $r,Model $x,string $type):JsonResponse{$rules=['name'=>['required','string','max:255'],'email'=>['nullable','email'],'phone'=>['nullable','string','max:50'],'address'=>['nullable','string'],'city'=>['nullable','string','max:100'],'country'=>['nullable','string','max:100'],'taxId'=>['nullable','string','max:100']];if($type==='supplier')$rules+=['tin'=>['nullable','string','max:100'],'vrn'=>['nullable','string','max:100'],'contactPerson'=>['nullable','string'],'paymentTerms'=>['nullable','string'],'notes'=>['nullable','string'],'rating'=>['nullable','numeric','between:0,5']];else $rules+=['customerType'=>['required',Rule::in(['retail','wholesale'])],'creditLimit'=>['nullable','numeric','min:0'],'discountRate'=>['nullable','numeric','between:0,100']];$d=$r->validate($rules);$map=['organization_id'=>$this->org($r),'name'=>$d['name'],'email'=>$d['email']??null,'phone'=>$d['phone']??null,'address'=>$d['address']??null,'city'=>$d['city']??null,'country'=>$d['country']??null,'tax_id'=>$d['taxId']??null];if($type==='supplier')$map+=['tin'=>$d['tin']??$d['taxId']??null,'vrn'=>$d['vrn']??null,'contact_person'=>$d['contactPerson']??null,'payment_terms'=>$d['paymentTerms']??null,'notes'=>$d['notes']??null,'rating'=>$d['rating']??5];else $map+=['customer_type'=>$d['customerType'],'credit_limit'=>$d['creditLimit']??0,'discount_rate'=>$d['discountRate']??0];$x->fill($map)->save();return response()->json($this->partyPayload($x),$x->wasRecentlyCreated?201:200);}
 private function saveWarehouse(Request $r,Warehouse $x):JsonResponse{$d=$r->validate(['name'=>['required','string','max:255'],'address'=>['nullable','string'],'city'=>['nullable','string'],'country'=>['nullable','string'],'phone'=>['nullable','string']]);$branchId=\App\Models\Branch::where('organization_id',$this->org($r))->value('id');abort_unless($branchId,422,'Create a branch before adding a warehouse.');$x->fill(['organization_id'=>$this->org($r),'branch_id'=>$branchId,'name'=>$d['name'],'code'=>$x->code?:'WH-'.str()->upper(str()->random(6)),'address'=>$d['address']??null,'phone'=>$d['phone']??null])->save();return response()->json(['_id'=>(string)$x->id,'name'=>$x->name,'address'=>$x->address,'city'=>$d['city']??null,'country'=>$d['country']??null,'phone'=>$x->phone,'isActive'=>$x->is_active],$x->wasRecentlyCreated?201:200);}
 private function categoryPayload(Category $x):array{return ['_id'=>(string)$x->id,'name'=>$x->name,'description'=>$x->description,'color'=>$x->color,'isActive'=>$x->is_active];} private function productPayload(Product $x):array{$stock=$x->relationLoaded('stockBalances')?$x->stockBalances:collect();$totalStock=$x->relationLoaded('stockBalances')?(float)$stock->sum('quantity'):(float)$x->stockBalances()->sum('quantity');return ['_id'=>(string)$x->id,'sku'=>$x->sku,'name'=>$x->name,'description'=>$x->description,'costPrice'=>(float)$x->cost_price,'sellingPrice'=>(float)$x->selling_price,'taxRate'=>(float)$x->tax_rate,'reorderLevel'=>(float)$x->reorder_level,'barcode'=>$x->barcode,'imageUrl'=>$x->image_url,'categoryId'=>$x->category_id?(string)$x->category_id:null,'category'=>$x->category?['_id'=>(string)$x->category->id,'name'=>$x->category->name]:null,'unitId'=>$x->unit_id?(string)$x->unit_id:null,'unit'=>$x->unit?['_id'=>(string)$x->unit->id,'name'=>$x->unit->name,'abbreviation'=>$x->unit->abbreviation]:null,'tags'=>$x->tags??[],'isActive'=>$x->is_active,'totalStock'=>$totalStock,'stock'=>$stock->map(fn($s)=>['_id'=>(string)$s->id,'warehouseId'=>(string)$s->warehouse_id,'warehouse'=>$s->warehouse?['_id'=>(string)$s->warehouse->id,'name'=>$s->warehouse->name]:null,'quantity'=>(float)$s->quantity,'reservedQuantity'=>0])->values()];} private function partyPayload(Model $x):array{return ['_id'=>(string)$x->id,'name'=>$x->name,'email'=>$x->email,'phone'=>$x->phone,'address'=>$x->address,'city'=>$x->city,'country'=>$x->country,'taxId'=>$x->tax_id,'tin'=>property_exists($x,'tin')?$x->tin:($x->tin??$x->tax_id),'vrn'=>property_exists($x,'vrn')?$x->vrn:($x->vrn??null),'contactPerson'=>$x->contact_person??null,'paymentTerms'=>$x->payment_terms??null,'notes'=>$x->notes??null,'rating'=>(float)($x->rating??0),'customerType'=>$x->customer_type??null,'creditLimit'=>(float)($x->credit_limit??0),'discountRate'=>(float)($x->discount_rate??0),'isActive'=>$x->is_active];}
}
