<?php
namespace App\Http\Controllers\Api\V1;
use App\Http\Controllers\Controller; use App\Models\{PriceList,PriceListItem}; use Illuminate\Http\{JsonResponse,Request}; use Illuminate\Validation\Rule;
class PriceListController extends Controller {
 public function index(Request $r):JsonResponse{$lists=PriceList::where('organization_id',$r->user()->organization_id)->withCount('items')->orderByDesc('year')->orderBy('name')->get();return response()->json($lists->map(fn($x)=>$this->listPayload($x)));}
 public function show(Request $r,PriceList $priceList):JsonResponse{$this->owned($r,$priceList);$priceList->load(['items'=>fn($q)=>$q->orderBy('item_type')->orderBy('description')]);return response()->json($this->listPayload($priceList)+['items'=>$priceList->items->map(fn($x)=>$this->itemPayload($x))]);}
 public function store(Request $r):JsonResponse{$d=$this->listData($r);$x=PriceList::create($d+['organization_id'=>$r->user()->organization_id]);return response()->json($this->listPayload($x),201);}
 public function update(Request $r,PriceList $priceList):JsonResponse{$this->owned($r,$priceList);$priceList->update($this->listData($r,$priceList));return response()->json($this->listPayload($priceList));}
 public function destroy(Request $r,PriceList $priceList):JsonResponse{$this->owned($r,$priceList);$priceList->delete();return response()->json(['deleted'=>true]);}
 public function storeItem(Request $r,PriceList $priceList):JsonResponse{$this->owned($r,$priceList);$x=$priceList->items()->create($this->itemData($r,$priceList));return response()->json($this->itemPayload($x),201);}
 public function updateItem(Request $r,PriceList $priceList,PriceListItem $item):JsonResponse{$this->owned($r,$priceList);abort_unless($item->price_list_id===$priceList->id,404);$item->update($this->itemData($r,$priceList,$item));return response()->json($this->itemPayload($item));}
 public function destroyItem(Request $r,PriceList $priceList,PriceListItem $item):JsonResponse{$this->owned($r,$priceList);abort_unless($item->price_list_id===$priceList->id,404);$item->delete();return response()->json(['deleted'=>true]);}
 private function listData(Request $r,?PriceList $x=null):array{return $r->validate(['name'=>['required','string','max:255',Rule::unique('price_lists')->where(fn($q)=>$q->where('organization_id',$r->user()->organization_id)->where('year',$r->input('year')))->ignore($x)],'year'=>['required','integer','between:2000,2100'],'currency'=>['required',Rule::in(['TSHS','USD','TZS'])],'effective_from'=>['nullable','date'],'effective_to'=>['nullable','date','after_or_equal:effective_from'],'is_active'=>['boolean']]);}
 private function itemData(Request $r,PriceList $list,?PriceListItem $x=null):array{return $r->validate(['product_id'=>['nullable','integer',Rule::exists('products','id')->where('organization_id',$r->user()->organization_id)],'item_code'=>['required','string','max:100',Rule::unique('price_list_items')->where('price_list_id',$list->id)->ignore($x)],'description'=>['required','string','max:255'],'item_type'=>['required','string','max:100'],'brand'=>['nullable','string','max:100'],'model'=>['nullable','string','max:100'],'unit'=>['required','string','max:50'],'unit_price'=>['required','numeric','min:0'],'vat_rate'=>['nullable','numeric','between:0,100'],'notes'=>['nullable','string']]);}
 private function owned(Request $r,PriceList $x):void{abort_unless($x->organization_id===$r->user()->organization_id,404);} private function listPayload(PriceList $x):array{return ['id'=>$x->id,'name'=>$x->name,'year'=>$x->year,'currency'=>$x->currency,'effective_from'=>$x->effective_from?->toDateString(),'effective_to'=>$x->effective_to?->toDateString(),'is_active'=>$x->is_active,'items_count'=>$x->items_count??$x->items()->count(),'created_at'=>$x->created_at?->toIso8601String()];} private function itemPayload(PriceListItem $x):array{return ['id'=>$x->id,'product_id'=>$x->product_id,'item_code'=>$x->item_code,'description'=>$x->description,'item_type'=>$x->item_type,'brand'=>$x->brand,'model'=>$x->model,'unit'=>$x->unit,'unit_price'=>(float)$x->unit_price,'vat_rate'=>(float)$x->vat_rate,'notes'=>$x->notes];}
}
