import { useRef, useState } from "react";
import { useLocation } from "react-router-dom";
import { apiClient, getApiErrorMessage } from "@/api/client.ts";
import { useAuth } from "@/hooks/use-auth.ts";
import { Button } from "@/components/ui/button.tsx";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog.tsx";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu.tsx";
import { Input } from "@/components/ui/input.tsx";
import { Download, FileSpreadsheet, FileText, Loader2, Upload } from "lucide-react";
import { toast } from "@/lib/system-message.ts";
import { loadBrandLogoDataUrl } from "@/lib/branding.ts";
import { downloadCorporateTablePdf } from "@/lib/pdf-design-system.ts";
type TableData={title:string;headers:string[];rows:string[][]};
const importResources:Record<string,string>={"/inventory":"products","/suppliers":"suppliers","/customers":"customers","/branches":"branches","/departments":"departments","/storage-locations":"warehouses","/warehouses":"warehouses"};
const slug=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
const visible=(element:HTMLElement)=>{const style=getComputedStyle(element);return style.display!=="none"&&style.visibility!=="hidden"&&element.offsetParent!==null};
function currentTable():TableData|null{const tables=Array.from(document.querySelectorAll("main table")).filter(table=>visible(table as HTMLElement));if(!tables.length)return null;const table=tables.sort((a,b)=>b.querySelectorAll("tbody tr").length-a.querySelectorAll("tbody tr").length)[0];const allHeaders=Array.from(table.querySelectorAll("thead th")).map(cell=>cell.textContent?.trim()||"");const indexes=allHeaders.map((header,index)=>({header,index})).filter(x=>x.header&&x.header.toLowerCase()!=="actions");const rows=Array.from(table.querySelectorAll("tbody tr")).filter(row=>visible(row as HTMLElement)).map(row=>{const cells=Array.from(row.querySelectorAll(":scope > td"));return indexes.map(({index})=>(cells[index]?.textContent??"").replace(/\s+/g," ").trim())});const title=document.querySelector("main h1, main h2")?.textContent?.trim()||"StockFlow Data";return{title,headers:indexes.map(x=>x.header),rows};}
function saveBlob(blob:Blob,filename:string){const url=URL.createObjectURL(blob);const link=document.createElement("a");link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
export function DataExchangeTools(){const location=useLocation();const {user}=useAuth();const isSuperAdmin=user?.role==="super_admin";const canExport=isSuperAdmin||user?.permissions.includes("data.export")===true;const resource=importResources[location.pathname];const canImport=Boolean(resource&&(isSuperAdmin||user?.permissions.includes("data.import")));const [open,setOpen]=useState(false);const [rows,setRows]=useState<Record<string,unknown>[]>([]);const [filename,setFilename]=useState("");const [busy,setBusy]=useState(false);const input=useRef<HTMLInputElement>(null);if(!canExport&&!canImport)return null;
 const authorize=async(format:"xlsx"|"pdf"|"doc")=>{const data=currentTable();if(!data||!data.headers.length)throw new Error("No visible data table is available on this page.");await apiClient.post("/data-exchange/export-authorize",{page:location.pathname,format});return data};
 const excel=async()=>{setBusy(true);toast.loading("Preparing Excel export...");try{const data=await authorize("xlsx");toast.loading("Building Excel file...");const XLSX=await import("xlsx");const workbook=XLSX.utils.book_new();const sheet=XLSX.utils.aoa_to_sheet([data.headers,...data.rows]);sheet["!cols"]=data.headers.map((header,index)=>({wch:Math.min(50,Math.max(header.length,...data.rows.map(row=>row[index]?.length??0))+2)}));XLSX.utils.book_append_sheet(workbook,sheet,"Data");XLSX.writeFile(workbook,`${slug(data.title)}.xlsx`);toast.success("Excel export created successfully")}catch(e){toast.error(getApiErrorMessage(e,"Excel export failed"))}finally{setBusy(false)}};
 const pdf=async()=>{setBusy(true);toast.loading("Preparing PDF export...");try{const data=await authorize("pdf");toast.loading("Generating PDF file...");await downloadCorporateTablePdf(data.title,data.headers,data.rows);toast.success("PDF export created successfully")}catch(e){toast.error(getApiErrorMessage(e,"PDF export failed"))}finally{setBusy(false)}};
 const word=async()=>{setBusy(true);toast.loading("Preparing Word export...");try{const data=await authorize("doc");toast.loading("Building Word file...");const esc=(v:string)=>v.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;");let logo="";try{logo=`<img src="${await loadBrandLogoDataUrl()}" style="height:42px;max-width:220px" />`}catch{}const html=`<html><head><meta charset="utf-8"><style>body{font-family:Arial}table{border-collapse:collapse;width:100%}th,td{border:1px solid #bbb;padding:6px;font-size:10pt}th{background:#059669;color:white}.brand{margin-bottom:16px}</style></head><body><div class="brand">${logo}</div><h1>${esc(data.title)}</h1><p>Generated ${new Date().toLocaleString()}</p><table><thead><tr>${data.headers.map(x=>`<th>${esc(x)}</th>`).join("")}</tr></thead><tbody>${data.rows.map(row=>`<tr>${row.map(x=>`<td>${esc(x)}</td>`).join("")}</tr>`).join("")}</tbody></table></body></html>`;saveBlob(new Blob(["\ufeff",html],{type:"application/msword"}),`${slug(data.title)}.doc`);toast.success("Word export created successfully")}catch(e){toast.error(getApiErrorMessage(e,"Word export failed"))}finally{setBusy(false)}};
 const readFile=async(file:File)=>{toast.loading("Reading import file...");try{const XLSX=await import("xlsx");const workbook=XLSX.read(await file.arrayBuffer(),{type:"array",cellDates:true});const sheet=workbook.Sheets[workbook.SheetNames[0]];const parsed=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:"",raw:false});if(!parsed.length)throw new Error("The selected file has no data rows.");if(parsed.length>5000)throw new Error("A maximum of 5,000 rows can be imported at once.");setRows(parsed);setFilename(file.name);setOpen(true);toast.success("File loaded and ready for review")}catch(e){toast.error(getApiErrorMessage(e,"Unable to read import file"))}finally{if(input.current)input.current.value=""}};
 const submit=async()=>{if(!resource)return;setBusy(true);toast.loading(`Importing ${resource}...`);try{const response=await apiClient.post<{data:{imported:number}}>(`/data-exchange/import/${resource}`,{rows});toast.success(`${response.data.data.imported} rows imported successfully`);setOpen(false);setRows([]);window.dispatchEvent(new Event("stockflow:api-invalidated"))}catch(e){toast.error(getApiErrorMessage(e,"Import failed. Check column names and values."))}finally{setBusy(false)}};
 return <><Input ref={input} type="file" className="hidden" accept=".csv,.xlsx,.xls" onChange={e=>{const file=e.target.files?.[0];if(file)void readFile(file)}}/><DropdownMenu><DropdownMenuTrigger asChild><Button variant="outline" size="sm" disabled={busy} className="inline-flex gap-2">{busy?<Loader2 className="size-4 animate-spin"/>:<FileSpreadsheet className="size-4"/>}<span className="hidden sm:inline">Data</span></Button></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-52"><DropdownMenuLabel>Data exchange</DropdownMenuLabel>{canExport&&<><DropdownMenuItem onClick={()=>void excel()}><FileSpreadsheet className="size-4"/>Export Excel (.xlsx)</DropdownMenuItem><DropdownMenuItem onClick={()=>void pdf()}><FileText className="size-4"/>Export PDF</DropdownMenuItem><DropdownMenuItem onClick={()=>void word()}><Download className="size-4"/>Export Word (.doc)</DropdownMenuItem></>}{canImport&&<><DropdownMenuSeparator/><DropdownMenuItem onClick={()=>input.current?.click()}><Upload className="size-4"/>Import CSV / Excel</DropdownMenuItem></>}</DropdownMenuContent></DropdownMenu><Dialog open={open} onOpenChange={setOpen}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>Import {resource} from {filename}</DialogTitle></DialogHeader><div className="space-y-3"><p className="text-sm text-muted-foreground">Review the first rows below. Import is transactional: if any row fails validation, nothing is saved.</p><div className="max-h-80 overflow-auto rounded-md border"><table className="w-full text-xs"><thead className="sticky top-0 bg-muted"><tr>{Object.keys(rows[0]??{}).map(key=><th key={key} className="px-3 py-2 text-left">{key}</th>)}</tr></thead><tbody>{rows.slice(0,8).map((row,index)=><tr key={index} className="border-t">{Object.keys(rows[0]??{}).map(key=><td key={key} className="whitespace-nowrap px-3 py-2">{String(row[key]??"")}</td>)}</tr>)}</tbody></table></div><p className="text-xs text-muted-foreground">{rows.length.toLocaleString()} rows ready · maximum 5,000 per import</p></div><DialogFooter><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={busy} onClick={()=>void submit()}>{busy?<Loader2 className="size-4 animate-spin"/>:<Upload className="size-4"/>}Import Data</Button></DialogFooter></DialogContent></Dialog></>;
}
