@component('emails.layouts.base', ['title' => $notification->title, 'preheader' => 'A new operational notification needs your attention.', 'accent' => '#4f7fe4'])
    <div style="display:inline-block; padding:6px 10px; border-radius:4px; background:#14264a; color:#9dbafa; font-size:11px; font-weight:700; letter-spacing:.4px; text-transform:uppercase;">Operational notification</div>
    <h1 style="margin:18px 0 10px; color:#f7f9fc; font-size:28px; line-height:1.2;">{{ $notification->title }}</h1>
    <p style="margin:0 0 22px; color:#9ba8ba; font-size:15px; line-height:1.7;">{{ $notification->message }}</p>
    @if($notification->action_url)
        @include('emails.components.button', ['url' => rtrim(config('app.frontend_url', config('app.url')), '/') . $notification->action_url, 'label' => 'Open workspace', 'color' => '#4f7fe4'])
    @endif
    <p style="margin:24px 0 0; color:#8090a7; font-size:12px; line-height:1.6;">This operational alert was generated by {{ config('app.name', 'StockFlow') }}.</p>
@endcomponent
