import { useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useApiQuery } from "@/hooks/use-api.ts";
import { endpoints } from "@/api/endpoints.ts";
import { apiClient } from "@/api/client.ts";
import { Button } from "@/components/ui/button.tsx";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card.tsx";
import { Badge } from "@/components/ui/badge.tsx";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs.tsx";
import { Skeleton } from "@/components/ui/skeleton.tsx";
import { toast } from "@/lib/system-message.ts";
import { ArrowLeft, Building2, Download, FileText, Files, Loader2, Mail, MapPin, Phone, ShieldCheck, Truck, Users, Warehouse } from "lucide-react";
import { DocumentViewer } from "@/components/documents/document-viewer.tsx";

type ProfileData = { supplier?: any; contacts?: any[]; commercialTerms?: any; mappings?: any[]; documents?: any[]; transactions?: any[]; stats?: any };

function money(value: unknown, currency = "TZS") { return `${currency} ${Number(value ?? 0).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`; }
function date(value: unknown) { return value ? new Date(String(value)).toLocaleDateString() : "—"; }

export default function SupplierProfilePage() {
  const navigate = useNavigate(); const { id } = useParams(); const [busy, setBusy] = useState<string | null>(null); const [previewDocument, setPreviewDocument] = useState<any | null>(null);
  const profile = useApiQuery(endpoints.suppliers.getProfile, id ? { supplierId: id } : "skip") as ProfileData | undefined;
  const supplier = profile?.supplier;
  const download = async (path: string, name: string, key: string) => { setBusy(key); try { const response = await apiClient.get(path, { responseType: "blob" }); const url = URL.createObjectURL(response.data); const link = document.createElement("a"); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); } catch { toast.error("Unable to download this document"); } finally { setBusy(null); } };
  if (profile === undefined) return <div className="space-y-5 p-6"><Skeleton className="h-10 w-64" /><Skeleton className="h-[620px]" /></div>;
  if (!supplier) return <div className="p-6"><Card><CardContent className="py-16 text-center">Supplier profile not found.</CardContent></Card></div>;
  const terms = profile.commercialTerms ?? {};
  const documents = profile.documents ?? [];
  return <div className="space-y-5 p-6 pb-24 md:pb-6">
    <div className="flex flex-wrap items-start justify-between gap-4"><div><Button variant="ghost" className="mb-2 -ml-3" onClick={() => navigate("/suppliers")}><ArrowLeft className="size-4" />Back to suppliers</Button><div className="flex items-center gap-3"><div className="flex size-11 items-center justify-center rounded-xl bg-primary/10 text-primary"><Building2 className="size-5" /></div><div><h1 className="text-2xl font-semibold">{supplier.name}</h1><p className="text-sm text-muted-foreground">Supplier Command Center · {supplier.currency ?? "TZS"}</p></div></div></div><div className="flex flex-wrap items-end justify-end gap-3"><Button variant="outline" onClick={() => navigate(`/suppliers/${supplier._id}/documents`)}><Files className="size-4" />Partnership documents</Button><div className="grid grid-cols-2 gap-2 text-right sm:grid-cols-4"><Metric label="Orders" value={profile.stats?.totalOrders ?? 0} /><Metric label="Spend" value={money(profile.stats?.totalSpend, supplier.currency)} /><Metric label="Paid" value={money(profile.stats?.totalPaid, supplier.currency)} /><Metric label="Outstanding" value={money(profile.stats?.outstanding, supplier.currency)} /></div></div></div>
    <Tabs defaultValue="general" className="space-y-4"><TabsList className="w-full justify-start overflow-x-auto"><TabsTrigger value="general">General Information</TabsTrigger><TabsTrigger value="contacts">Contact Roster</TabsTrigger><TabsTrigger value="terms">Commercial Terms</TabsTrigger><TabsTrigger value="catalog">Product Catalog Mapping</TabsTrigger><TabsTrigger value="documents">Document Vault</TabsTrigger><TabsTrigger value="transactions">Transaction History</TabsTrigger></TabsList>
      <TabsContent value="general"><div className="grid gap-4 lg:grid-cols-[1.2fr_.8fr]"><Card><CardHeader><CardTitle className="text-base">Legal and company details</CardTitle><CardDescription>Verified supplier identity and internal relationship notes.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2"><Info icon={<MapPin />} label="Legal address" value={[supplier.legalAddress, supplier.city, supplier.country].filter(Boolean).join(", ")} /><Info icon={<ShieldCheck />} label="Tax ID / TIN" value={supplier.tin ?? supplier.taxId} /><Info icon={<ShieldCheck />} label="VAT / VRN" value={supplier.vrn} /><Info icon={<Warehouse />} label="Currency" value={supplier.currency ?? "TZS"} /><Info icon={<Mail />} label="Primary email" value={supplier.email} /><Info icon={<Phone />} label="Primary phone" value={supplier.phone} /></CardContent></Card><Card><CardHeader><CardTitle className="text-base">Internal notes</CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm text-muted-foreground">{supplier.notes || "No internal notes recorded."}</p></CardContent></Card></div></TabsContent>
      <TabsContent value="contacts"><Card><CardHeader><CardTitle className="text-base">Contact roster</CardTitle><CardDescription>Sales, support, accounting and other direct supplier contacts.</CardDescription></CardHeader><CardContent><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{(profile.contacts ?? []).map((contact) => <div key={contact.id} className="rounded-xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{contact.name}</p><p className="text-xs text-primary">{contact.role || "General contact"}</p></div>{contact.is_primary && <Badge>Primary</Badge>}</div><div className="mt-4 space-y-2 text-sm text-muted-foreground">{contact.email && <p className="flex items-center gap-2"><Mail className="size-3.5" />{contact.email}</p>}{contact.phone && <p className="flex items-center gap-2"><Phone className="size-3.5" />{contact.phone}</p>}{contact.notes && <p className="border-t pt-2 text-xs">{contact.notes}</p>}</div></div>)}{!(profile.contacts ?? []).length && <Empty icon={<Users />} text="No supplier contacts have been added yet." />}</div></CardContent></Card></TabsContent>
      <TabsContent value="terms"><Card><CardHeader><CardTitle className="text-base">Commercial terms</CardTitle><CardDescription>Pricing, order minimums and preferred delivery arrangements.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Info label="Currency" value={terms.currency ?? supplier.currency ?? "TZS"} /><Info label="Payment terms" value={terms.payment_terms ?? supplier.paymentTerms} /><Info label="Minimum order quantity" value={terms.minimum_order_quantity ?? "Not specified"} /><Info icon={<Truck />} label="Preferred shipping" value={terms.preferred_shipping_method ?? "Not specified"} /><div className="rounded-xl border p-4 sm:col-span-2"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Pricing tiers</p><pre className="mt-2 whitespace-pre-wrap text-sm">{terms.pricing_tiers ? JSON.stringify(terms.pricing_tiers, null, 2) : "No pricing tiers recorded."}</pre></div><div className="rounded-xl border p-4 sm:col-span-2"><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Volume discounts</p><pre className="mt-2 whitespace-pre-wrap text-sm">{terms.volume_discounts ? JSON.stringify(terms.volume_discounts, null, 2) : "No volume discounts recorded."}</pre></div></CardContent></Card></TabsContent>
      <TabsContent value="catalog"><Card><CardHeader><CardTitle className="text-base">Product catalog mapping</CardTitle><CardDescription>Supplier SKUs, current prices and mappings to internal inventory SKUs.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/50 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-3 py-3">Supplier SKU / part</th><th className="px-3 py-3">Description</th><th className="px-3 py-3">Internal SKU</th><th className="px-3 py-3 text-right">Unit price</th><th className="px-3 py-3">Conversion</th></tr></thead><tbody>{(profile.mappings ?? []).map((mapping) => <tr key={mapping.id} className="border-t"><td className="px-3 py-3 font-mono text-xs">{mapping.supplierSku}<br /><span className="text-muted-foreground">{mapping.supplierPartNumber || "—"}</span></td><td className="px-3 py-3">{mapping.supplierDescription || mapping.product?.name || "—"}</td><td className="px-3 py-3 font-mono text-xs">{mapping.product?.sku || "Unmapped"}</td><td className="px-3 py-3 text-right font-medium">{mapping.unitPrice == null ? "Not set" : money(mapping.unitPrice, mapping.currency ?? supplier.currency)}</td><td className="px-3 py-3">{mapping.unitConversion ?? 1}×</td></tr>)}</tbody></table>{!(profile.mappings ?? []).length && <Empty text="No SKU mappings recorded yet." />}</div></CardContent></Card></TabsContent>
      <TabsContent value="documents"><Card><CardHeader><CardTitle className="text-base">Document vault</CardTitle><CardDescription>Contracts, compliance certificates and insurance documents with expiry monitoring.</CardDescription></CardHeader><CardContent className="space-y-3">{documents.map((document) => <div key={document.id} className="flex flex-wrap items-center gap-3 rounded-xl border p-4"><div className="flex size-10 items-center justify-center rounded-lg bg-muted"><FileText className="size-5 text-primary" /></div><div className="min-w-0 flex-1"><p className="truncate font-medium">{document.title}</p><p className="text-xs text-muted-foreground">{document.type} · {document.name} · expires {date(document.expiresAt)}</p></div><Badge variant={document.expiryStatus === "expired" ? "destructive" : document.expiryStatus === "expiring" ? "secondary" : "outline"}>{document.expiryStatus === "none" ? "No expiry" : document.expiryStatus}</Badge><Button variant="ghost" size="icon" title="View document" aria-label="View document" onClick={() => setPreviewDocument(document)}><FileText className="size-4" /></Button><Button variant="outline" size="sm" disabled={busy === document.id} onClick={() => void download(document.downloadPath, document.name, document.id)}>{busy === document.id ? <Loader2 className="size-4 animate-spin" /> : <Download className="size-4" />}Download</Button></div>)}{!documents.length && <Empty icon={<FileText />} text="No supplier documents have been uploaded yet." />}</CardContent></Card></TabsContent>
      <TabsContent value="transactions"><Card><CardHeader><CardTitle className="text-base">Transaction history</CardTitle><CardDescription>Purchase orders, returns and invoices linked to this supplier.</CardDescription></CardHeader><CardContent><div className="overflow-x-auto"><table className="w-full text-sm"><thead className="bg-muted/50 text-left text-xs uppercase text-muted-foreground"><tr><th className="px-3 py-3">Type</th><th className="px-3 py-3">Reference</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Date</th><th className="px-3 py-3 text-right">Amount</th></tr></thead><tbody>{(profile.transactions ?? []).map((transaction) => <tr key={transaction.id} className="border-t"><td className="px-3 py-3 capitalize">{String(transaction.type).replaceAll("_", " ")}</td><td className="px-3 py-3 font-mono text-xs">{transaction.reference}</td><td className="px-3 py-3"><Badge variant="outline">{transaction.status}</Badge></td><td className="px-3 py-3 text-muted-foreground">{date(transaction.date)}</td><td className="px-3 py-3 text-right font-medium">{transaction.amount == null ? "—" : money(transaction.amount, supplier.currency)}</td></tr>)}</tbody></table>{!(profile.transactions ?? []).length && <Empty text="No transactions linked to this supplier yet." />}</div></CardContent></Card></TabsContent>
    </Tabs>
    <DocumentViewer document={previewDocument} onOpenChange={setPreviewDocument} />
  </div>;
}

function Metric({ label, value }: { label: string; value: unknown }) { return <div><p className="text-[10px] uppercase tracking-wide text-muted-foreground">{label}</p><p className="mt-1 text-sm font-semibold">{String(value)}</p></div>; }
function Info({ label, value, icon }: { label: string; value: unknown; icon?: React.ReactNode }) { return <div className="rounded-xl border p-3"><p className="flex items-center gap-2 text-xs uppercase tracking-wide text-muted-foreground">{icon && <span className="size-3.5">{icon}</span>}{label}</p><p className="mt-2 break-words text-sm font-medium">{String(value || "—")}</p></div>; }
function Empty({ text, icon }: { text: string; icon?: React.ReactNode }) { return <div className="py-12 text-center text-sm text-muted-foreground">{icon && <span className="mx-auto mb-2 block w-fit">{icon}</span>}{text}</div>; }
